### ISSUE TITLE
`User` sounds more like a variable rather than a function name. Give better names to functions. Something like `getUserName` perhaps.

### ISSUE THREAD

**Issue by Keshavdulal** [sbimochan/react-api#14]
https://github.com/sbimochan/react-api/blob/1af7a36594eea672eb58fcedcd8ab0d655043cf4/src/components/TodoList.js#L6

**Comment by sbimochan** [comment]
I'm little confuse here. I was trying to create stateless component so that I could call below like:
<**User** description={}/>
If I changed function name to _getUser_ it would be:
<**getUser** description={}/>

**Comment by Keshavdulal** [comment]
Oh, I didn't realize that you were using the method as a stateless component earlier. My bad here.
