### ISSUE TITLE
Make this one-liner

### ISSUE THREAD

**Issue by Keshavdulal** [sbimochan/react-api#7]
```
this.handleInputChange = this.handleInputChange.bind(this);
```
Usually, we have a lot of bindings in react so, making this one-liner will help to minimize the code itself.

https://github.com/sbimochan/react-api/blob/1af7a36594eea672eb58fcedcd8ab0d655043cf4/src/components/Create.js#L12

**Comment by sbimochan** [comment]
done. thank you
